name: zodgame

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# 核心修改：在这里添加全局权限，允许 Action 写入仓库和更新工作流
permissions:
  contents: write
  actions: write
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.9"
        cache: "pip"
    - name: Install requirements
      run: |
        pip3 install -r ./zodgame/requirements.txt
    - name: Run 
      run: |
        python3 ./zodgame/zodgame.py "${{secrets.ZODGAME_COOKIE}}"
    - name: Keepalive Workflow
      uses: liskin/gh-workflow-keepalive@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
